/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type FriendRequestTransformer from '#transformers/friend_request_transformer'
import type GroupDetailTransformer from '#transformers/group_detail_transformer'
import type GroupInviteTransformer from '#transformers/group_invite_transformer'
import type GroupTransformer from '#transformers/group_transformer'
import type PublicUserTransformer from '#transformers/public_user_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type FriendRequest = InferData<FriendRequestTransformer>
  export namespace FriendRequest {
    export type Variants = InferVariants<FriendRequestTransformer>
  }
  export type GroupDetail = InferData<GroupDetailTransformer>
  export namespace GroupDetail {
    export type Variants = InferVariants<GroupDetailTransformer>
  }
  export type GroupInvite = InferData<GroupInviteTransformer>
  export namespace GroupInvite {
    export type Variants = InferVariants<GroupInviteTransformer>
  }
  export type Group = InferData<GroupTransformer>
  export namespace Group {
    export type Variants = InferVariants<GroupTransformer>
  }
  export type PublicUser = InferData<PublicUserTransformer>
  export namespace PublicUser {
    export type Variants = InferVariants<PublicUserTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
