/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ChatMessageTransformer from '#transformers/chat_message_transformer'
import type FriendRequestTransformer from '#transformers/friend_request_transformer'
import type FriendTransformer from '#transformers/friend_transformer'
import type GroupDetailTransformer from '#transformers/group_detail_transformer'
import type GroupInviteTransformer from '#transformers/group_invite_transformer'
import type GroupTransformer from '#transformers/group_transformer'
import type MatchTransformer from '#transformers/match_transformer'
import type ModerationActionTransformer from '#transformers/moderation_action_transformer'
import type ModerationUserTransformer from '#transformers/moderation_user_transformer'
import type PublicUserTransformer from '#transformers/public_user_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type ChatMessage = InferData<ChatMessageTransformer>
  export namespace ChatMessage {
    export type Variants = InferVariants<ChatMessageTransformer>
  }
  export type FriendRequest = InferData<FriendRequestTransformer>
  export namespace FriendRequest {
    export type Variants = InferVariants<FriendRequestTransformer>
  }
  export type Friend = InferData<FriendTransformer>
  export namespace Friend {
    export type Variants = InferVariants<FriendTransformer>
  }
  export type GroupDetail = InferData<GroupDetailTransformer>
  export namespace GroupDetail {
    export type Variants = InferVariants<GroupDetailTransformer>
  }
  export type GroupInvite = InferData<GroupInviteTransformer>
  export namespace GroupInvite {
    export type Variants = InferVariants<GroupInviteTransformer>
  }
  export type Group = InferData<GroupTransformer>
  export namespace Group {
    export type Variants = InferVariants<GroupTransformer>
  }
  export type Match = InferData<MatchTransformer>
  export namespace Match {
    export type Variants = InferVariants<MatchTransformer>
  }
  export type ModerationAction = InferData<ModerationActionTransformer>
  export namespace ModerationAction {
    export type Variants = InferVariants<ModerationActionTransformer>
  }
  export type ModerationUser = InferData<ModerationUserTransformer>
  export namespace ModerationUser {
    export type Variants = InferVariants<ModerationUserTransformer>
  }
  export type PublicUser = InferData<PublicUserTransformer>
  export namespace PublicUser {
    export type Variants = InferVariants<PublicUserTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
