import { join } from 'node:path'
import { avatarDirectory } from '#services/avatar_storage'
import type { HttpContext } from '@adonisjs/core/http'

/**
 * Filenames are generated by the avatar storage service (cuid + image
 * extension), so anything else is rejected before touching the disk.
 */
const STORED_AVATAR_PATTERN = /^[a-z0-9]+\.(jpg|jpeg|png|webp)$/

export default class AvatarsController {
  /**
   * Streams a stored avatar image from local disk.
   */
  async show({ params, response }: HttpContext) {
    const fileName = String(params.filename)

    if (!STORED_AVATAR_PATTERN.test(fileName)) {
      return response.notFound({ error: 'Avatar not found' })
    }

    return response.download(join(avatarDirectory(), fileName))
  }
}
