/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameMatchIdRouteImport } from './routes/game.$matchId'
import { Route as AppTipsRouteImport } from './routes/_app.tips'
import { Route as AppSignupRouteImport } from './routes/_app.signup'
import { Route as AppSigninRouteImport } from './routes/_app.signin'
import { Route as AppRulesRouteImport } from './routes/_app.rules'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppAuthRouteImport } from './routes/_app._auth'
import { Route as AppAuthSettingsRouteImport } from './routes/_app._auth.settings'
import { Route as AppAuthPlayRouteImport } from './routes/_app._auth.play'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameMatchIdRoute = GameMatchIdRouteImport.update({
  id: '/game/$matchId',
  path: '/game/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTipsRoute = AppTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSigninRoute = AppSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthSettingsRoute = AppAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthPlayRoute = AppAuthPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof AppContactRoute
  '/privacy': typeof AppPrivacyRoute
  '/rules': typeof AppRulesRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/tips': typeof AppTipsRoute
  '/game/$matchId': typeof GameMatchIdRoute
  '/play': typeof AppAuthPlayRoute
  '/settings': typeof AppAuthSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof AppContactRoute
  '/privacy': typeof AppPrivacyRoute
  '/rules': typeof AppRulesRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/tips': typeof AppTipsRoute
  '/game/$matchId': typeof GameMatchIdRoute
  '/play': typeof AppAuthPlayRoute
  '/settings': typeof AppAuthSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/contact': typeof AppContactRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/signin': typeof AppSigninRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/tips': typeof AppTipsRoute
  '/game/$matchId': typeof GameMatchIdRoute
  '/_app/_auth/play': typeof AppAuthPlayRoute
  '/_app/_auth/settings': typeof AppAuthSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/rules'
    | '/signin'
    | '/signup'
    | '/tips'
    | '/game/$matchId'
    | '/play'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/rules'
    | '/signin'
    | '/signup'
    | '/tips'
    | '/game/$matchId'
    | '/play'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/contact'
    | '/_app/privacy'
    | '/_app/rules'
    | '/_app/signin'
    | '/_app/signup'
    | '/_app/tips'
    | '/game/$matchId'
    | '/_app/_auth/play'
    | '/_app/_auth/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GameMatchIdRoute: typeof GameMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$matchId': {
      id: '/game/$matchId'
      path: '/game/$matchId'
      fullPath: '/game/$matchId'
      preLoaderRoute: typeof GameMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tips': {
      id: '/_app/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof AppTipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signin': {
      id: '/_app/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AppSigninRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/settings': {
      id: '/_app/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppAuthSettingsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/play': {
      id: '/_app/_auth/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppAuthPlayRouteImport
      parentRoute: typeof AppAuthRoute
    }
  }
}

interface AppAuthRouteChildren {
  AppAuthPlayRoute: typeof AppAuthPlayRoute
  AppAuthSettingsRoute: typeof AppAuthSettingsRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthPlayRoute: AppAuthPlayRoute,
  AppAuthSettingsRoute: AppAuthSettingsRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppContactRoute: typeof AppContactRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSigninRoute: typeof AppSigninRoute
  AppSignupRoute: typeof AppSignupRoute
  AppTipsRoute: typeof AppTipsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppContactRoute: AppContactRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRulesRoute: AppRulesRoute,
  AppSigninRoute: AppSigninRoute,
  AppSignupRoute: AppSignupRoute,
  AppTipsRoute: AppTipsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GameMatchIdRoute: GameMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
